sudo: true
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.1"
before_install:
    - sudo add-apt-repository ppa:rethinkdb/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install rethinkdb -y
before_script:
  - cp config-example.json config.json
  - rethinkdb --daemon
after_script:
  - npm run coveralls
matrix:
  fast_finish: true